[package]
name = "seamd"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
image = { version = "0.25.6", features = ["rayon"] }
rayon = "1.10.0"
